### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by shirsho-12** [shirsho-12/CS4248_NLP#13]
These are tasks that we most likely won't have time for, but will attempt if we can:
- [ ] #6 KL Divergence SBERT
- [ ] #11 Transformer Model Swap
- [ ] #12 DeText Model Swap
- [ ] #14 TextRank Model
- [ ] #15 Unsupervised Graph Neural Network
