### ISSUE TITLE
Core 

### ISSUE THREAD

**Issue by shirsho-12** [shirsho-12/CS4248_NLP#23]
Implement core functionality to start running tests and generating results:
- [x] #18 ELCo Dataloader
- [ ] #17 Metrics for Testing
- [x] #21 ELCoM Baseline Model (Unsupervised)
- [ ] #22 Teacher-Student Model (Supervised)
